python codegen.py dwarf_whatform Dwarf_Attribute Dwarf_Half > out
python codegen.py dwarf_whatform_direct Dwarf_Attribute Dwarf_Half >> out
python codegen.py dwarf_whatattr Dwarf_Attribute Dwarf_Half >> out
python codegen.py dwarf_formref Dwarf_Attribute Dwarf_Off >> out
python codegen.py dwarf_global_formref Dwarf_Attribute Dwarf_Off >> out
python codegen.py dwarf_formaddr Dwarf_Attribute Dwarf_Addr >> out
python codegen.py dwarf_formflag Dwarf_Attribute Dwarf_Bool >> out
python codegen.py dwarf_formudata Dwarf_Attribute Dwarf_Unsigned >> out
python codegen.py dwarf_formsdata Dwarf_Attribute Dwarf_Signed >> out
