Vagrant.configure("2") do |config|
  config.vm.define "fbsd_12_4" do |c|
    c.vm.box = "rbspy/FreeBSD-12.4-STABLE"
  end

  config.vm.define "fbsd_13_2" do |c|
    c.vm.box = "rbspy/FreeBSD-13.2-STABLE"
  end

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [".git", ".vagrant.d"]

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 3
  end
end
